name: Documentation

on:
  release:
    types:
      - released

concurrency:
  group: 'docs'

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

env:
  GIT_EMAIL: ${{ vars.GIT_EMAIL }}
  GIT_USERNAME: ${{ vars.GIT_USERNAME }}
  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build docs
        run: npm run build:docs
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

  deploy_docs:
    runs-on: ubuntu-latest
    needs: build_docs
    env:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2


