name: Release

on:
  push:
    branches: [master]

concurrency:
  group: 'release'

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write

env:
  GIT_EMAIL: ${{ vars.GIT_EMAIL }}
  GIT_USERNAME: ${{ vars.GIT_USERNAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Test
        run: npm run test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  publish_package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Publish package
        run: |
          npm run build
          npx semantic-release


