name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

env:
  GIT_EMAIL: ${{ vars.GIT_EMAIL }}
  GIT_USERNAME: ${{ vars.GIT_USERNAME }}
  DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Test
        run: npm run test

  danger_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Danger CI
        run: npm run danger-ci

  build_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build package
        run: npm run build

