name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Test
        run: npm run test
      - uses: codecov/codecov-action@v3

  build_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Build package
        run: npm run build

